alter table TM_TASK add constraint FK_TM_TASK_CREDIT_APPLICATION_ID foreign key (CREDIT_APPLICATION_ID) references CREDIT_CREDIT_REQUEST(CARD_ID);
create index IDX_TM_TASK_CREDIT_APPLICATION on TM_TASK (CREDIT_APPLICATION_ID);
