alter table CREDIT_CREDIT_REQUEST add constraint FK_CREDIT_CREDIT_REQUEST_BORROWER_ID foreign key (BORROWER_ID) references DF_CONTRACTOR(CORRESPONDENT_ID);
create index IDX_CREDIT_CREDIT_REQUEST_BORROWER on CREDIT_CREDIT_REQUEST (BORROWER_ID);
