-- begin CREDIT_CREDIT
alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_CREDIT_TYPE_ID foreign key (CREDIT_TYPE_ID) references CREDIT_CREDIT_TYPE(ID)^
alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_BANK_ID foreign key (BANK_ID) references DF_BANK(ID)^
alter table CREDIT_CREDIT add constraint FK_CREDIT_CREDIT_CARD_ID foreign key (CARD_ID) references WF_CARD(ID)^
create index IDX_CREDIT_CREDIT_CREDIT_TYPE on CREDIT_CREDIT (CREDIT_TYPE_ID)^
create index IDX_CREDIT_CREDIT_BANK on CREDIT_CREDIT (BANK_ID)^
-- end CREDIT_CREDIT
-- begin CREDIT_CREDIT_REQUEST
alter table CREDIT_CREDIT_REQUEST add constraint FK_CREDIT_CREDIT_REQUEST_CREDIT_ID foreign key (CREDIT_ID) references CREDIT_CREDIT(CARD_ID)^
alter table CREDIT_CREDIT_REQUEST add constraint FK_CREDIT_CREDIT_REQUEST_BORROWER_ID foreign key (BORROWER_ID) references DF_CONTRACTOR(CORRESPONDENT_ID)^
alter table CREDIT_CREDIT_REQUEST add constraint FK_CREDIT_CREDIT_REQUEST_CARD_ID foreign key (CARD_ID) references DF_DOC(CARD_ID)^
create index IDX_CREDIT_CREDIT_REQUEST_BORROWER on CREDIT_CREDIT_REQUEST (BORROWER_ID)^
create index IDX_CREDIT_CREDIT_REQUEST_CREDIT on CREDIT_CREDIT_REQUEST (CREDIT_ID)^
-- end CREDIT_CREDIT_REQUEST
-- begin TM_TASK
alter table TM_TASK add constraint FK_TM_TASK_CREDIT_APPLICATION_ID foreign key (CREDIT_APPLICATION_ID) references CREDIT_CREDIT_REQUEST(CARD_ID)^
create index IDX_TM_TASK_CREDIT_APPLICATION on TM_TASK (CREDIT_APPLICATION_ID)^
-- end TM_TASK
